

# View
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Game
FPS = 60

# Badgers
BADGER_DIST_FROM_EDGE = 200
MIN_BADGER_POS = BADGER_DIST_FROM_EDGE
MAX_BADGER_POS = SCREEN_HEIGHT - BADGER_DIST_FROM_EDGE
BADGER_SPEED = 200 / FPS
SCROLL_SPEED = 100 / FPS
BADGER_SPAWN_TIME = 1500
BADGER_SPAWN_HEIGHT = SCREEN_HEIGHT // 2

# Sar
SAR_CENTER = (SCREEN_WIDTH - 100, SCREEN_HEIGHT // 2)

# Colors
GRASS = (0, 150, 0)
