

# View
import pygame.font

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Game
FPS = 60

# Badgers
BADGER_DIST_FROM_EDGE = 200
MIN_BADGER_POS = BADGER_DIST_FROM_EDGE
MAX_BADGER_POS = SCREEN_HEIGHT - BADGER_DIST_FROM_EDGE
BADGER_SPEED_SCALE = 50 / FPS
SCROLL_SPEED = 100 / FPS
BADGER_SPAWN_TIME = 1500
BADGER_SPAWN_HEIGHT = MIN_BADGER_POS
IDEAL_BADGER_HEIGHT = SCREEN_HEIGHT // 2

# Sar
SAR_CENTER = (SCREEN_WIDTH - 100, SCREEN_HEIGHT // 2)

# Colors
GRASS = (0, 150, 0)
TEXT = (0, 50, 0)

# Text
pygame.font.init()
SCORE_FONT = pygame.font.SysFont('sans-serif', 72)
BUTTON_FONT = pygame.font.SysFont('sans-serif', 36)
SCORE_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
REPLAY_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 + 50)
QUIT_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2 + 100)
REPLAY = BUTTON_FONT.render('REPLAY', True, TEXT)
QUIT = BUTTON_FONT.render('QUIT', True, TEXT)
